title: OpenHellion
description: OpenHellion website.
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
url: https://openhellion.github.io/
repository: "OpenHellion/openhellion.github.io"

minimal_mistakes_skin: "dirt"

include: ["_pages", "_docs" ]
encoding: "utf-8"

plugins:
  - jekyll-include-cache

defaults:
  - scope:
      path: "docs"
    values:
      toc: true
      layout: "posts"
      classes:
        - wide
      sidebar:
        nav: "docs"
  - scope:
      path: "pages"
    values:
      layout: single
