title: OpenHellion
description: OpenHellion website.
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
url: https://openhellion.github.io/
repository: "OpenHellion/openhellion.github.io"

minimal_mistakes_skin: "dirt"

include: ["_pages", "_docs" ]

plugins:
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: docs
    values:
      toc: true
      classes:
        - wide
      sidebar:
        nav: "docs"
  - scope:
      path: ""
      type: pages
    values:
      layout: single
